[package]
name = "anlg-audio-interface"
version = "0.1.0"
edition = "2024"

[features]
default = ["rodio"]
rodio = ["dep:dasp", "dep:rodio"]

[dependencies]
dasp = { version = "0.11.0", features = ["interpolate", "interpolate-linear"], optional = true }
futures-util = "0.3.31"
rodio = { version = "0.22", features = ["tracing"], optional = true }
